services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: api_salles
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/api_salles
      JWT_SECRET: super-secret-jwt
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  db_data:
